Lesson 3 code execution
DolgihOlga/js-home-tasks-OlgaDolgih pull request #2
Opened 2022-02-10 17:04 UTC by DolgihOlga

Lesson 3 code execution

2022-02-13 11:30 UTC, instinct-it-academy approved these changes, later dismissed
Доброе утро, задание пока что на доработку, обратите внимание на комментарии.

2022-02-13 11:30 UTC, instinct-it-academy commented on lesson-3-code-execution/js.js
> +"use strict"
пожалуйста каждую задачу в отдельный файл

2022-02-13 11:30 UTC, instinct-it-academy commented on lesson-3-code-execution/js.js
> +}*/
нужно переписать ) решение должно быть универсальным т.е. подходить для любого кол-ва элементов хэша. Обратите внимание на пример выполнения.

2022-02-13 11:30 UTC, instinct-it-academy commented on lesson-3-code-execution/js.js
> +    if (nums === '' || nums === null || isNaN(nums)) {
попробуйте перенести данное условие в условие остановки цикла, т.е. уйти от бесконечного цикла и сделать явную проверку.

2022-02-13 11:32 UTC, instinct-it-academy requested changes
Корректный статус для задания

2022-02-13 12:51 UTC, DolgihOlga commented
Добрый день! Задания исправила.

On Sun, Feb 13, 2022 at 2:32 PM instinct-it-academy <
***@***.***> wrote:

> ***@***.**** requested changes on this pull request.
>
> Корректный статус для задания
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/DolgihOlga/js-home-tasks-OlgaDolgih/pull/2#pullrequestreview-880969425>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AK57H5CQ2XRIAYZGLG5Z5VTU26JETANCNFSM5OBMEZCA>
> .
> Triage notifications on the go with GitHub Mobile for iOS
> <https://apps.apple.com/app/apple-store/id1477376905?ct=notification-email&mt=8&pt=524675>
> or Android
> <https://play.google.com/store/apps/details?id=com.github.android&referrer=utm_campaign%3Dnotification-email%26utm_medium%3Demail%26utm_source%3Dgithub>.
>
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>

2022-02-26 21:13 UTC, instinct-it-academy approved these changes

2022-02-26 21:13 UTC, merged